language: java
services:
  - docker
jdk:
  - oraclejdk11
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
install:
  - ./gradlew check
jobs:
  include:
  - stage: "Unit Tests"
    script:
    - ./gradlew test
  #- stage: "Deploy to GCP"
before_install:
  - docker build -t z-sport-backend .
  - docker images

