language: java
services:
  - docker
env:
  global:
  - PATH=$PATH:$HOME/google-cloud-sdk/bin
  - PROJECT_ID="z-sport-frontend-test"
  - ZONE="europe-west1-c"
  - IMAGE_NAME=z-sport-backend:latest
  - GOOGLE_APPLICATION_CREDENTIALS="client-secret.json"
  - CLUSTER_NAME=z-sport-backend-cluster
  - FULL_IMAGE_NAME=gcr.io/devops-workshops-for-schools/$IMAGE_NAME
jdk:
  - oraclejdk11
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/google-cloud-sdk/
before_install:
  - ls -la
  - openssl aes-256-cbc -K $encrypted_21af30358e49_key -iv $encrypted_21af30358e49_iv -in client-secret.json.enc -out client-secret.json -d
install:
  - ./gradlew build
before_script:
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)";
  - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list;
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -;
  - sudo apt-get update && sudo apt-get install google-cloud-sdk;
  - sudo apt-get update && sudo apt-get install kubectl
jobs:
  include:
    #- stage: "Unit Tests"
    #  script:
    #    - ./gradlew test
    - stage: "Deploy containers to GCP"
      script:
        - docker images
        - docker build -t $FULL_IMAGE_NAME .
        - docker images
        - gcloud auth activate-service-account travis-kubernetes-service-acc@devops-workshops-for-schools.iam.gserviceaccount.com --key-file=client-secret.json
        - gcloud docker -- push $FULL_IMAGE_NAME
        - gcloud container clusters get-credentials z-sport-backend-cluster --zone europe-west1-c --project devops-workshops-for-schools
        - kubectl run z-sport-backend-container --image=gcr.io/devops-workshops-for-schools/z-sport-backend:latest --port 8080
        #- kubectl expose deployment z-sport-backend-container --type=LoadBalancer --port 80 --target-port 8080


